### ISSUE TITLE
taskfile does not work with nvm

### ISSUE THREAD

**Issue by ssbarnea** [muehlemann-popp/html-to-pdf#4]
That might come as a weird bug report but you are the first person that used nvm inside taskfile and I was looking to do the same. Sadly, I soon found out that your implementation does not really work (at least not for me).

I am on macos with m1 and when that is what I got:
```
$ task build:local
bash: line 4: nvm: command not found
```

nvm is installed and working locally but I do not know why it did not work with your cool NODE_ENV approach.

PS. That is also related to https://github.com/go-task/task/discussions/773

**Comment by olegstepura** [comment]
Hi, Sorin!

Thanks for the issue report and sorry for long answer. Did you try running `task init:local` before running `task start:local`?
I just tried running it locally on intel mac and it works fine. I would try reinstalling nvm maybe.

**Comment by ssbarnea** [comment]
I tried and got the same errors, even on a Fedora box. During the last few weeks I was able to find a way to make it work, but the code that works is little bit different than yours: https://github.com/ansible/ansible-language-server/blob/main/Taskfile.yml#L12-L14

Did you spot the lack of double `$$`? They are not needed. In fact I was wondering how did it happen that it worked for you.

**Comment by olegstepura** [comment]
For me both run fine. I created #5 to fix it for you. I think it's a safe change.
